swagger: '2.0'
info:
  version: 1.0.0
  title: JooqSwagger
  description: testign
host: 'localhost:9090'
basePath: /jooqswagger
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/xml
  - application/json
paths:
  /getall:
    get:
      tags:
        - getall
      summary: "gets all"
      operationId: "getall"
      description: ""
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/GroupDto'
            xml:
              name: AllGroups
              wrapped: true
  /get:
    get:
      tags:
        - getone
      summary: "gets one"
      operationId: "getone"
      description: "gets one"
      parameters:
        - name: id
          in: query
          description: ID of author
          required: true
          type: integer
          default: 1
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GroupDto'
  /put:
    post:
      tags:
        - post
      summary: "adds"
      operationId: "add"
      description: "adds group"
      parameters:
        - name: id
          in: query
          description: ID of author
          required: true
          type: integer
          default: 1
        - name: fn
          in: query
          description: fn of author
          required: true
          type: string
          default: ''
        - name: ln
          in: query
          description: ln of author
          required: true
          type: string
          default: ''
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GroupDto'

definitions:
  GroupDto:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
        minLength: 1
        maxLength: 254